### ISSUE TITLE
Calculate age

### ISSUE THREAD

**Issue by ProjectawDeveloper** [ProjectawDeveloper/beginner-coding-problems#15]
Problem: Calculate John's age in years as of `"2020-10-18T14:30:00.000Z"`. 

The input should be an object containing information about John and a second argument containing the date at which his date of birth should be calculated.

Input:
```
{
firstName: "John",
lastName: "Doe",
dateOfBirth: "1990-01-01T14:00:00.000Z"
},
"2020-10-18T14:30:00.000Z"
```

expected: `30`

**Comment by bayucakra20** [comment]
Hi, i'd would like to work on this issue
