### ISSUE TITLE
Sort numbers

### ISSUE THREAD

**Issue by ProjectawDeveloper** [ProjectawDeveloper/beginner-coding-problems#2]
**Problem**: Sort number in array in ascending order.

**input**: solve([5, 4, 8, 40, 100, 44])

**expected**: [4, 5, 8, 40, 44, 100]

**Comment by alokkumarak** [comment]
@ProjectawDeveloper   Can you assign it to me?

**Comment by ghanender-chauhan** [comment]
Can u assign me this i will do in python

**Comment by ProjectawDeveloper** [comment]
@ghanender-chauhan Sorry a PR has already been raised for this.

**Comment by ghanender-chauhan** [comment]
> @ghanender-chauhan Sorry a PR has already been raised for this.

check if its wrong then please assign me
