### ISSUE TITLE
Sort numbers descending

### ISSUE THREAD

**Issue by ProjectawDeveloper** [ProjectawDeveloper/beginner-coding-problems#3]
**Problem**: Sort number in array in descending order.

**input**: solve([5, 4, 8, 40, 100, 44])

**expected**: [100, 44, 40, 8, 5, 4]

**Comment by bayucakra20** [comment]
Hi, I'd would like to work on this issue

**Comment by ghanender-chauhan** [comment]
Hi, Please Assign me this . I will do in python
