### ISSUE TITLE
First element in array

### ISSUE THREAD

**Issue by ProjectawDeveloper** [ProjectawDeveloper/beginner-coding-problems#8]
**Problem:** Return the latest date in the array

**Input:** solve(["2020-10-10T11:10:33.226Z", "2020-10-11T11:10:33.226Z", "2020-10-12T11:10:33.226Z"])

**expected:** "2020-10-12T11:10:33.226Z"

**Comment by Ashwalls93** [comment]
Can i do this?

**Comment by Ashwalls93** [comment]
Should this be expecting the earliest date not latest?
